#!/usr/bin/env python3
"""
캐릭터 이미지를 Base64 data URL로 변환하여 characters_base64.json 생성.

Whisk 웹페이지 컨텍스트에서 로컬 파일 경로를 fetch할 수 없으므로,
이미지를 Base64로 변환하여 Chrome 확장 프로그램에서 직접 사용 가능하게 함.

사용법:
    python scripts/convert_characters.py
    python scripts/convert_characters.py --output popup/characters_base64.js
"""

import argparse
import base64
import json
import sys
from pathlib import Path
from typing import Optional

WHISK_BASE = Path.home() / "Projects/코딩/youtube-factory/outputs/whisk"
CHARACTERS_DIR = WHISK_BASE / "yonga" / "characters"

# 캐릭터 매핑: key -> (한글이름, 이미지파일명, 별명들, 설명)
CHARACTER_MAP = {
    "yonga": ("용아", "용아_상반신.png", ["용아", "yonga", "龍兒"], "20대 청년, 검은 단발, 금색 세로동공, 무협 복장"),
    "soso": ("소소", "소소_상반신.png", ["소소", "soso"], "어린 아이"),
    "master": ("취광도인", "취광도인_상반신.png", ["취광도인", "스승", "master", "취광"], "중년 도인, 술병, 도복"),
    "soyeon": ("소연", "소연_상반신.png", ["소연", "soyeon"], "20세 여성, 단발 보브컷, 화산파 제복, 검"),
    "yeomchang": ("염창", "염창_상반신.png", ["염창", "yeomchang"], "마교 사천왕, 붉은 갑옷, 적염창, 화기 사용"),
    "cheolmuyeong": ("철무영", "철무영_상반신.png", ["철무영", "cheolmuyeong", "무영"], "넓은 어깨, 검객, 묵직한 체격"),
    "dogryeon": ("독련", "독련_상반신.png", ["독련", "dogryeon"], "독을 사용하는 무인"),
    "noehwang": ("뇌황", "뇌황_상반신.png", ["뇌황", "noehwang"], "번개 기술 사용자"),
    "heukyeom": ("흑염교주", "흑염교주_상반신.png", ["흑염교주", "heukyeom", "교주"], "마교 교주, 흑염 사용"),
    "amyeong": ("암영", "암영_상반신.png", ["암영", "amyeong"], "암살 전문 무인"),
    "dangcheonro": ("당천로", "당천로_상반신.png", ["당천로", "dangcheonro"], "당가 원로, 인자한 할아버지"),
    "dangmugyeol": ("당무결", "당무결_상반신.png", ["당무결", "dangmugyeol"], "당가 소가주, 의리 있는 해독 전문가"),
    "dangsohwa": ("당소화", "당소화_상반신.png", ["당소화", "dangsohwa"], "당무결의 여동생, 활발한 해독 천재"),
    "doglang": ("독랑", "독랑_상반신.png", ["독랑", "doglang"], "독련의 추적자, 야수적 사냥꾼"),
    "hyeolyeong": ("혈영", "혈영_상반신.png", ["혈영", "hyeolyeong"], "독련의 심복, 잔인한 암살자"),
    "jegalhwi": ("제갈휘", "제갈휘_상반신.png", ["제갈휘", "jegalhwi"], "제갈세가 가주, 온화한 학자"),
    "jegalmyeong": ("제갈명", "제갈명_상반신.png", ["제갈명", "jegalmyeong"], "제갈세가 젊은 책사, 냉철하지만 정의로움"),
}

SCENES_DIR = WHISK_BASE / "yonga" / "scenes"
STYLES_DIR = WHISK_BASE / "yonga" / "styles"

# 스타일 레퍼런스 이미지 (Whisk 스타일 슬롯용)
STYLE_REFERENCE = STYLES_DIR / "당소화_전신.png"

# 장면 매핑: key -> (한글이름, 이미지파일명 or None, 별명들, 설명)
# 이미지파일명이 None이면 빈 image로 생성 (나중에 이미지 추가 가능)
SCENE_MAP = {
    "murimmaeng": ("무림맹", None, ["무림맹", "murimmaeng"], "무림맹 본산"),
    "master_house": ("스승의집", None, ["스승의집", "취광도인집", "사부집"], "취광도인의 거처"),
    "dark_alley": ("암흑가", None, ["암흑가", "암흑거리"], "암흑가 뒷골목"),
    "dangga": ("당가", None, ["당가", "사천당가"], "사천당가 본산"),
    "cliff": ("절벽", None, ["절벽", "낭떠러지"], "높은 절벽/낭떠러지"),
    "inn": ("객잔", None, ["객잔", "주막"], "무림 객잔/주막"),
}


def image_to_base64(filepath: Path) -> Optional[str]:
    """이미지 파일을 Base64 data URL로 변환."""
    if not filepath.exists():
        print(f"  [SKIP] 파일 없음: {filepath.name}", file=sys.stderr)
        return None

    with open(filepath, "rb") as f:
        data = base64.b64encode(f.read()).decode("utf-8")

    suffix = filepath.suffix.lower()
    mime_types = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp"}
    mime = mime_types.get(suffix, "image/png")

    return f"data:{mime};base64,{data}"


def convert_all() -> dict:
    """모든 캐릭터 이미지를 Base64로 변환."""
    result = {}

    for key, (name, filename, aliases, description) in CHARACTER_MAP.items():
        filepath = CHARACTERS_DIR / filename
        print(f"  [{key}] {name}: {filename}", end=" ... ")

        data_url = image_to_base64(filepath)
        if data_url:
            size_kb = len(data_url) // 1024
            print(f"OK ({size_kb}KB)")
            result[key] = {
                "name": name,
                "aliases": aliases,
                "image": data_url,
                "description": description,
            }
        else:
            print("SKIP")

    return result


def convert_scenes() -> dict:
    """장면 이미지를 Base64로 변환. 이미지 없으면 빈 문자열."""
    result = {}

    for key, (name, filename, aliases, description) in SCENE_MAP.items():
        data_url = ""
        if filename:
            filepath = SCENES_DIR / filename
            print(f"  [장면:{key}] {name}: {filename}", end=" ... ")
            data_url = image_to_base64(filepath) or ""
            if data_url:
                size_kb = len(data_url) // 1024
                print(f"OK ({size_kb}KB)")
            else:
                print("SKIP (이미지 없음, 빈 슬롯)")
        else:
            print(f"  [장면:{key}] {name}: (이미지 미등록)")

        result[key] = {
            "name": name,
            "aliases": aliases,
            "image": data_url,
            "description": description,
        }

    return result


def generate_js_module(characters: dict, scenes: dict, style_image: str, output_path: Path):
    """JavaScript 모듈로 출력 (popup.js에서 import 가능)."""
    lines = ["// Auto-generated by convert_characters.py", "// DO NOT EDIT MANUALLY", ""]

    # 스타일 레퍼런스
    lines.append(f'const STYLE_REFERENCE_BASE64 = "{style_image}";')
    lines.append("")

    lines.append("const CHARACTER_BASE64 = {")

    # 캐릭터
    for key, data in characters.items():
        name = data["name"]
        aliases_str = json.dumps(data["aliases"], ensure_ascii=False)
        desc = data["description"]
        lines.append(f'  "{name}": {{')
        lines.append(f'    image: "{data["image"]}",')
        lines.append(f"    aliases: {aliases_str},")
        lines.append(f'    description: "{desc}"')
        lines.append("  },")

    # 장면
    if scenes:
        lines.append("")
        lines.append("  // === 장면 (Scene) ===")
        lines.append('  // type: "scene" 으로 캐릭터와 구분')
        for key, data in scenes.items():
            name = data["name"]
            aliases_str = json.dumps(data["aliases"], ensure_ascii=False)
            desc = data["description"]
            image = data["image"]
            lines.append(f'  "{name}": {{')
            lines.append(f'    image: "{image}",')
            lines.append(f"    aliases: {aliases_str},")
            lines.append(f'    type: "scene",')
            lines.append(f'    description: "{desc}"')
            lines.append("  },")

    lines.append("};")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    size_mb = output_path.stat().st_size / (1024 * 1024)
    print(f"\n  JS 파일 생성: {output_path} ({size_mb:.1f}MB)")


def generate_json(characters: dict, output_path: Path):
    """JSON 파일로 출력."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(characters, ensure_ascii=False, indent=2), encoding="utf-8")

    size_mb = output_path.stat().st_size / (1024 * 1024)
    print(f"\n  JSON 파일 생성: {output_path} ({size_mb:.1f}MB)")


def main():
    parser = argparse.ArgumentParser(description="캐릭터 이미지 Base64 변환")
    parser.add_argument("--output", "-o", default="popup/characters_base64.js",
                        help="출력 파일 경로 (기본: popup/characters_base64.js)")
    parser.add_argument("--json", action="store_true",
                        help="JSON 형식으로도 출력")
    args = parser.parse_args()

    project_root = Path(__file__).parent.parent
    output_path = project_root / args.output

    print(f"캐릭터 이미지 디렉토리: {CHARACTERS_DIR}")
    print(f"출력 파일: {output_path}\n")

    if not CHARACTERS_DIR.exists():
        print(f"ERROR: 디렉토리가 존재하지 않습니다: {CHARACTERS_DIR}", file=sys.stderr)
        sys.exit(1)

    characters = convert_all()

    if not characters:
        print("\nERROR: 변환된 캐릭터가 없습니다.", file=sys.stderr)
        sys.exit(1)

    print(f"\n총 {len(characters)}개 캐릭터 변환 완료")

    # 장면 변환
    print(f"\n장면 이미지 디렉토리: {SCENES_DIR}")
    scenes = convert_scenes()
    print(f"총 {len(scenes)}개 장면 등록 완료")

    # 스타일 레퍼런스 변환
    style_image = ""
    print(f"\n스타일 레퍼런스: {STYLE_REFERENCE}")
    if STYLE_REFERENCE.exists():
        style_image = image_to_base64(STYLE_REFERENCE) or ""
        if style_image:
            size_kb = len(style_image) // 1024
            print(f"  OK ({size_kb}KB)")
        else:
            print("  SKIP")
    else:
        print("  파일 없음, 건너뜀")

    generate_js_module(characters, scenes, style_image, output_path)

    if args.json:
        json_path = output_path.with_suffix(".json")
        generate_json(characters, json_path)

    # characters.json도 업데이트 (Base64 이미지 포함)
    chars_json_path = project_root / "characters.json"
    generate_json(characters, chars_json_path)
    print(f"  characters.json 업데이트 완료")


if __name__ == "__main__":
    main()
